server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # user service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        # expense service
        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/expenses/**
            - Path=/api/v1/expenses/**
        # discovery server service
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # discovery server static resource route
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
